service: 'wietbot-commands-eval-node-2'

provider:
    name: 'aws'
    runtime: 'nodejs12.x'
    region: 'eu-west-1'
    memorySize: '256'
    timeout: '10'
    
    environment:
        heater_warmupAware: 'true'
    
    vpc:
        securityGroupIds:
            - 'sg-4fdd0307'
        subnetIds:
            - 'subnet-41e1c709'
            - 'subnet-2ca23276'
            - 'subnet-99faadff'

package:
    exclude:
        - '.idea/**'
        - '.serverless/**'

functions:
    evalNodePrivate:
        handler: 'handler.evalNodePrivate'
