service: 'wietbot-commands-hangman'

provider:
    name: 'aws'
    runtime: 'java8'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '10'

    environment:

    iamRoleStatements:

    vpc:
        securityGroupIds:
            - 'sg-4fdd0307'
        subnetIds:
            - 'subnet-41e1c709'
            - 'subnet-2ca23276'
            - 'subnet-99faadff'
custom:
    version: '1.0.0-SNAPSHOT'

package:
    artifact: 'target/commands-hangman-core-${self:custom.version}-jar-with-dependencies.jar'

functions:
