service: 'wietbot-commands-hangman'

provider:
    name: 'aws'
    runtime: 'java11'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '60'

    environment:
        service__name: '${self:service}'
        heater_warmupAware: 'true'
        database_host: '${ssm:/me/wietlol/wietbot/common/database/host}'
        database_name: '${ssm:/me/wietlol/wietbot/common/database/name}'
        database_driver: '${ssm:/me/wietlol/wietbot/common/database/driver}'
        database_user: '${ssm:/me/wietlol/wietbot/common/database/user}'
        database_password: '${ssm:/me/wietlol/wietbot/common/database/password}'

    iamRoleStatements:
        -   Effect: 'Allow'
            Action:
                - 'rds-db:connect'
            Resource:
                - '*'
        -   Effect: 'Allow'
            Action:
                - 'lambda:InvokeFunction'
            Resource:
                - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-services-chat-client-dev-sendMessage'

plugins:
    - 'serverless-plugin-log-retention'
    - 'serverless-log-forwarding'

custom:
    version: '1.0.0'
    logRetentionInDays: '3'
    logForwarding:
        destinationARN: 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-data-log-dev-saveLogsCloudwatch'
        filterPattern: '{ $.severity.value >= 0 }'

package:
    artifact: 'target/commands-hangman-core-${self:custom.version}.jar'

functions:
    play:
        handler: 'me.wietlol.wietbot.commands.hangman.core.api.HangmanHandler::playSns'
        events:
            -   sns:
                    arn: !Ref CommandsHangman
                    topicName: 'wietbot-commands-hangman'

resources:
    Resources:
        CommandsHangman:
            Type: 'AWS::SNS::Topic'
            Properties:
                TopicName: 'wietbot-commands-hangman'
