service: 'wietbot-__maven-project-name__'

provider:
    name: 'aws'
    runtime: 'java11'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '60'

    environment:
        service__name: '${self:service}'
        heater_warmupAware: 'true'

    iamRoleStatements:

    vpc:

plugins:
    - 'serverless-plugin-log-retention'
    - 'serverless-log-forwarding'

custom:
    version: '1.0.0-SNAPSHOT'
    logRetentionInDays: '3'
    logForwarding:
        destinationARN: 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-data-log-dev-saveLogsCloudwatch'
        filterPattern: '{ $.severity.value >= 0 }'

package:
    artifact: 'target/__maven-project-name__-core-${self:custom.version}.jar'

functions:
