service: 'wietbot-commands-abbreviation'

provider:
    name: 'aws'
    runtime: 'java8'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '60'

    environment:

    iamRoleStatements:

custom:
    version: '1.0.0-SNAPSHOT'

package:
    artifact: 'target/commands-abbreviation-core-${self:custom.version}-jar-with-dependencies.jar'

functions:
