service: 'wietbot-services-chat-client'

provider:
    name: 'aws'
    runtime: 'java11'
    region: 'eu-west-1'
    memorySize: '1024'
    timeout: '60'

    environment:
        service__name: '${self:service}'
        heater_warmupAware: 'true'
        seCredentials_emailAddress: '${ssm:/me/wietlol/wietbot/services/stackexchange/wietbot/emailAddress}'
        seCredentials_password: '${ssm:/me/wietlol/wietbot/services/stackexchange/wietbot/password}'

plugins:
    - 'serverless-plugin-log-retention'
    - 'serverless-log-forwarding'

custom:
    version: '1.0.0'
    logRetentionInDays: '3'
    logForwarding:
        destinationARN: 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-data-log-dev-saveLogsCloudwatch'
        filterPattern: '{ $.severity.value >= 0 }'

package:
    artifact: 'target/services-chat-client-core-${self:custom.version}.jar'

functions:
    sendMessage:
        handler: 'me.wietlol.wietbot.services.chatclient.core.api.ChatClientHandler::sendMessageBit'
    editMessage:
        handler: 'me.wietlol.wietbot.services.chatclient.core.api.ChatClientHandler::editMessageBit'
