service: 'wietbot-commands-eval-node'

provider:
    name: 'aws'
    runtime: 'java8'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '20'

    environment:
        heater_warmupAware: 'true'

    iamRoleStatements:
        -   Effect: 'Allow'
            Action:
                - 'lambda:InvokeFunction'
            Resource:
                - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-commands-eval-node-2-dev-evalNodePrivate'
                - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-services-chat-client-dev-sendMessage'

custom:
    version: '1.0.0-SNAPSHOT'

package:
    artifact: 'target/commands-eval-node-core-${self:custom.version}-jar-with-dependencies.jar'

functions:
    evalNode:
        handler: 'me.wietlol.wietbot.commands.evalnode.core.api.EvalNodeHandler::evalNodeSns'
        events:
            -   sns:
                    arn: !Ref CommandsEvalNode
                    topicName: 'wietbot-commands-evalNode'

resources:
    Resources:
        CommandsEvalNode:
            Type: 'AWS::SNS::Topic'
            Properties:
                TopicName: 'wietbot-commands-evalNode'
