service: 'wietbot-commands-eval-javascript'

provider:
    name: 'aws'
    runtime: 'java11'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '10'

    environment:
        service__name: '${self:service}'
        heater_warmupAware: 'true'

    iamRoleStatements:

plugins:
    - 'serverless-plugin-log-retention'
    - 'serverless-log-forwarding'
    - 'serverless-iam-roles-per-function'

custom:
    version: '1.0.0'
    logRetentionInDays: '3'
    logForwarding:
        destinationARN: 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-data-log-dev-saveLogsCloudwatch'
        filterPattern: '{ $.severity.value >= 0 }'

package:
    artifact: 'target/commands-eval-javascript-core-${self:custom.version}.jar'

functions:
    evalJavascript:
        handler: 'me.wietlol.wietbot.commands.evaljavascript.core.api.EvalJavascriptHandler::evalJavascriptSns'
        timeout: '30'
        events:
            -   sns:
                    arn: !Ref CommandsEvalJavascript
                    topicName: 'wietbot-commands-evalJavascript'
        iamRoleStatements:
            -   Effect: 'Allow'
                Action:
                    - 'lambda:InvokeFunction'
                Resource:
                    - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-commands-eval-javascript-dev-evalJavascriptPrivate'
                    - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-services-chat-client-dev-sendMessage'
    evalJavascriptPrivate:
        handler: 'me.wietlol.wietbot.commands.evaljavascript.core.api.EvalJavascriptPrivateHandler::evalJavascriptPrivate'
        vpc:
            securityGroupIds:
                - 'sg-4fdd0307'
            subnetIds:
                - 'subnet-41e1c709'
                - 'subnet-2ca23276'
                - 'subnet-99faadff'

resources:
    Resources:
        CommandsEvalJavascript:
            Type: 'AWS::SNS::Topic'
            Properties:
                TopicName: 'wietbot-commands-evalJavascript'
