service: 'wietbot-commands-eval-javascript'

provider:
    name: 'aws'
    runtime: 'java8'
    region: 'eu-west-1'
    memorySize: '512'
    timeout: '10'

    environment:
        heater_warmupAware: 'true'

    iamRoleStatements:

custom:
    version: '1.0.0-SNAPSHOT'

plugins:
    localPath: 'C:/Users/Harry/AppData/Roaming/npm/node_modules'
    modules:
        - 'serverless-iam-roles-per-function'

package:
    artifact: 'target/commands-eval-javascript-core-${self:custom.version}-jar-with-dependencies.jar'

functions:
    evalJavascript:
        handler: 'me.wietlol.wietbot.commands.evaljavascript.core.api.EvalJavascriptHandler::evalJavascriptSns'
        timeout: '20'
        events:
            -   sns:
                    arn: !Ref CommandsEvalJavascript
                    topicName: 'wietbot-commands-evalJavascript'
        iamRoleStatements:
            -   Effect: 'Allow'
                Action:
                    - 'lambda:InvokeFunction'
                Resource:
                    - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-commands-eval-javascript-dev-evalJavascriptPrivate'
                    - 'arn:aws:lambda:eu-west-1:059598504952:function:wietbot-services-chat-client-dev-sendMessage'
    evalJavascriptPrivate:
        handler: 'me.wietlol.wietbot.commands.evaljavascript.core.api.EvalJavascriptPrivateHandler::evalJavascriptPrivate'
        vpc:
            securityGroupIds:
                - 'sg-4fdd0307'
            subnetIds:
                - 'subnet-41e1c709'
                - 'subnet-2ca23276'
                - 'subnet-99faadff'

resources:
    Resources:
        CommandsEvalJavascript:
            Type: 'AWS::SNS::Topic'
            Properties:
                TopicName: 'wietbot-commands-evalJavascript'
